### ISSUE TITLE
credhub fails to start after upgrading from kit v1.14.0 to 1.15.1

### ISSUE THREAD

**Issue by naveedahd** [genesis-community/bosh-genesis-kit#98]
Got the following error after upgrading the `bosh-genesis-kit` from v1.4.0 to v1.15.1

```
Task 2200973 | 15:54:55 | Preparing deployment: Preparing deployment (00:00:01)
Task 2200973 | 15:54:56 | Preparing deployment: Rendering templates (00:00:00)
Task 2200973 | 15:54:57 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 2200973 | 15:54:57 | Updating instance bosh: bosh/29daa24b-38f2-4b23-92a9-5c394f4dc1fa (1) (canary) (00:10:59)
                     L Error: 'bosh/29daa24b-38f2-4b23-92a9-5c394f4dc1fa (1)' is not running after update. Review logs for failed jobs: credhub
Task 2200973 | 16:05:56 | Error: 'bosh/29daa24b-38f2-4b23-92a9-5c394f4dc1fa (1)' is not running after update. Review logs for failed jobs: credhub

Task 2200973 Started  Tue Aug  4 15:54:55 UTC 2020
Task 2200973 Finished Tue Aug  4 16:05:56 UTC 2020
Task 2200973 Duration 00:11:01
Task 2200973 error

Updating deployment:
  Expected task '2200973' to succeed but state is 'error'

Exit code 1
```

The detailed credhub log shows it's due to a flyway exception:

```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-08-04T15:35:29.734Z [main] .... ERROR --- SpringApplication: Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Found non-empty schema(s) "public" but no schema history table. Use baseline() or set baselineOnMigrate to true to initialize the schema history table.
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1108) ~[spring-context-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868) ~[spring-context-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) [spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
	at org.cloudfoundry.credhub.CredHubApp.main(CredHubApp.java:20) [classes!/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_252]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_252]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_252]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [credhub.jar:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [credhub.jar:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) [credhub.jar:?]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) [credhub.jar:?]
Caused by: org.flywaydb.core.api.FlywayException: Found non-empty schema(s) "public" but no schema history table. Use baseline() or set baselineOnMigrate to true to initialize the schema history table.
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:187) ~[flyway-core-6.4.4.jar!/:?]
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:159) ~[flyway-core-6.4.4.jar!/:?]
	at org.flywaydb.core.Flyway.execute(Flyway.java:530) ~[flyway-core-6.4.4.jar!/:?]
	at org.flywaydb.core.Flyway.migrate(Flyway.java:159) ~[flyway-core-6.4.4.jar!/:?]
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:65) ~[spring-boot-autoconfigure-2.2.7.RELEASE.jar!/:2.2.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792) ~[spring-beans-5.2.6.RELEASE.jar!/:5.2.6.RELEASE]
	... 26 more
2020-08-04T15:35:38.019Z [main] ....  INFO --- CredHubApp: Starting CredHubApp on localhost with PID 14077 (/var/vcap/data/packages/credhub/39cc7ce6a1a743958e78843f125ef4a2a9cd294b/credhub.jar started by vcap in /var/vcap/data/packages/credhub/39cc7ce6a1a743958e78843f125ef4a2a9cd294b)
2020-08-04T15:35:38.030Z [main] ....  INFO --- CredHubApp: The following profiles are active: prod
2020-08-04T15:35:40.263Z [main] ....  INFO --- RepositoryConfigurationDelegate: Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2020-08-04T15:35:40.498Z [main] ....  INFO --- RepositoryConfigurationDelegate: Finished Spring Data repository scanning in 222ms. Found 5 JPA repository interfaces.
2020-08-04T15:35:41.703Z [main] ....  INFO --- TomcatWebServer: Tomcat initialized with port(s): 8844 (https)
2020-08-04T15:35:41.726Z [main] ....  INFO --- Http11NioProtocol: Initializing ProtocolHandler ["https-jsse-nio-8844"]
2020-08-04T15:35:41.729Z [main] ....  INFO --- StandardService: Starting service [Tomcat]
2020-08-04T15:35:41.732Z [main] ....  INFO --- StandardEngine: Starting Servlet engine: [Apache Tomcat/9.0.34]
2020-08-04T15:35:41.839Z [main] ....  INFO --- [/]: Initializing Spring embedded WebApplicationContext
2020-08-04T15:35:41.839Z [main] ....  INFO --- ContextLoader: Root WebApplicationContext: initialization completed in 3740 ms
2020-08-04T15:35:42.377Z [main] ....  WARN --- JwtAccessTokenConverter: Unable to create an RSA verifier from verifierKey (ignoreable if using MAC)
2020-08-04T15:35:42.874Z [main] ....  INFO --- VersionPrinter: Flyway Community Edition 6.4.4 by Redgate
2020-08-04T15:35:42.916Z [main] ....  INFO --- HikariDataSource: HikariPool-1 - Starting...
2020-08-04T15:35:43.125Z [main] ....  INFO --- HikariDataSource: HikariPool-1 - Start completed.
2020-08-04T15:35:43.185Z [main] ....  INFO --- DatabaseFactory: Database: jdbc:postgresql://127.0.0.1:5432/credhub (PostgreSQL 10.12)
2020-08-04T15:35:43.291Z [main] ....  INFO --- DbValidate: Successfully validated 72 migrations (execution time 00:00.064s)
2020-08-04T15:35:43.302Z [main] ....  WARN --- AnnotationConfigServletWebServerApplicationContext: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Found non-empty schema(s) "public" but no schema history table. Use baseline() or set baselineOnMigrate to true to initialize the schema history table.
2020-08-04T15:35:43.302Z [main] ....  INFO --- HikariDataSource: HikariPool-1 - Shutdown initiated...
2020-08-04T15:35:43.312Z [main] ....  INFO --- HikariDataSource: HikariPool-1 - Shutdown completed.
2020-08-04T15:35:43.318Z [main] ....  INFO --- StandardService: Stopping service [Tomcat]
2020-08-04T15:35:43.340Z [main] ....  INFO --- ConditionEvaluationReportLoggingListener:
```

**Comment by naveedahd** [comment]
The following bug in Credhub 2.7.0 seems to be the main culprit:

https://www.pivotaltracker.com/n/projects/1977341/stories/173911070

Credhub's release seems to have resolved the issue:

https://github.com/pivotal/credhub-release/releases/tag/2.8.0

**Comment by thomasmitchell** [comment]
rad lol

can you PR the credhub bump to this kit and link this issue pleaseeeee :)
